apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-data
  namespace: airport
spec:
  storageClassName: manual
  volumeName: oracle-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
