apiVersion: v1
kind: Secret
metadata:
  name: airport-secrets
  namespace: airport
type: Opaque
stringData:
  DB_USERNAME: AIRPORT_APP
  DB_PASSWORD: Airport12345
  ORACLE_PASSWORD: OracleRoot123
  JWT_SECRET: replace-this-with-a-64-character-production-secret-before-apply
