CREATE SEQUENCE SEQ_USERS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AIRPORTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AIRCRAFT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FLIGHTS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SEATS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESERVATIONS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENTS START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE APP_USERS (
  ID NUMBER(19) PRIMARY KEY,
  FULL_NAME VARCHAR2(160) NOT NULL,
  EMAIL VARCHAR2(180) NOT NULL,
  PASSWORD_HASH VARCHAR2(120) NOT NULL,
  ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('ADMIN','CLIENT')),
  PHONE VARCHAR2(40),
  DOCUMENT_ID VARCHAR2(60),
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX IX_USERS_EMAIL ON APP_USERS (EMAIL);

CREATE TABLE AIRPORTS (
  ID NUMBER(19) PRIMARY KEY,
  NAME VARCHAR2(180) NOT NULL,
  CITY VARCHAR2(120) NOT NULL,
  COUNTRY VARCHAR2(120) NOT NULL,
  IATA_CODE VARCHAR2(3) NOT NULL
);
CREATE UNIQUE INDEX IX_AIRPORT_IATA ON AIRPORTS (IATA_CODE);

CREATE TABLE AIRCRAFT (
  ID NUMBER(19) PRIMARY KEY,
  MODEL VARCHAR2(120) NOT NULL,
  CAPACITY NUMBER(10) NOT NULL CHECK (CAPACITY > 0),
  AIRLINE VARCHAR2(140) NOT NULL
);

CREATE TABLE FLIGHTS (
  ID NUMBER(19) PRIMARY KEY,
  ORIGIN_ID NUMBER(19) NOT NULL,
  DESTINATION_ID NUMBER(19) NOT NULL,
  AIRCRAFT_ID NUMBER(19) NOT NULL,
  DEPARTURE_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
  ARRIVAL_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
  PRICE NUMBER(12,2) NOT NULL CHECK (PRICE > 0),
  AVAILABLE_SEATS NUMBER(10) NOT NULL CHECK (AVAILABLE_SEATS >= 0),
  STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('SCHEDULED','BOARDING','DEPARTED','ARRIVED','CANCELLED')),
  CONSTRAINT FK_FLIGHT_ORIGIN FOREIGN KEY (ORIGIN_ID) REFERENCES AIRPORTS(ID),
  CONSTRAINT FK_FLIGHT_DESTINATION FOREIGN KEY (DESTINATION_ID) REFERENCES AIRPORTS(ID),
  CONSTRAINT FK_FLIGHT_AIRCRAFT FOREIGN KEY (AIRCRAFT_ID) REFERENCES AIRCRAFT(ID),
  CONSTRAINT CK_FLIGHT_TIME CHECK (ARRIVAL_TIME > DEPARTURE_TIME)
);
CREATE INDEX IX_FLIGHT_ROUTE_DATE ON FLIGHTS (ORIGIN_ID, DESTINATION_ID, DEPARTURE_TIME);
CREATE INDEX IX_FLIGHT_STATUS ON FLIGHTS (STATUS);

CREATE TABLE SEATS (
  ID NUMBER(19) PRIMARY KEY,
  FLIGHT_ID NUMBER(19) NOT NULL,
  SEAT_NUMBER VARCHAR2(8) NOT NULL,
  RESERVED NUMBER(1) DEFAULT 0 NOT NULL CHECK (RESERVED IN (0,1)),
  CONSTRAINT FK_SEAT_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE,
  CONSTRAINT UK_SEAT_FLIGHT_NUMBER UNIQUE (FLIGHT_ID, SEAT_NUMBER)
);

CREATE TABLE RESERVATIONS (
  ID NUMBER(19) PRIMARY KEY,
  CODE VARCHAR2(24) NOT NULL,
  USER_ID NUMBER(19) NOT NULL,
  FLIGHT_ID NUMBER(19) NOT NULL,
  SEAT_ID NUMBER(19) NOT NULL,
  STATUS VARCHAR2(30) NOT NULL CHECK (STATUS IN ('PENDING_PAYMENT','CONFIRMED','REJECTED','CANCELLED')),
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT FK_RES_USER FOREIGN KEY (USER_ID) REFERENCES APP_USERS(ID),
  CONSTRAINT FK_RES_FLIGHT FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID),
  CONSTRAINT FK_RES_SEAT FOREIGN KEY (SEAT_ID) REFERENCES SEATS(ID)
);
CREATE UNIQUE INDEX IX_RESERVATION_CODE ON RESERVATIONS (CODE);

CREATE TABLE PAYMENTS (
  ID NUMBER(19) PRIMARY KEY,
  RESERVATION_ID NUMBER(19) NOT NULL,
  AMOUNT NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('APPROVED','REJECTED')),
  AUTHORIZATION_CODE VARCHAR2(40) NOT NULL,
  CARD_LAST4 VARCHAR2(4) NOT NULL,
  CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT FK_PAYMENT_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(ID),
  CONSTRAINT UK_PAYMENT_RESERVATION UNIQUE (RESERVATION_ID)
);
