INSERT INTO APP_USERS (ID, FULL_NAME, EMAIL, PASSWORD_HASH, ROLE, PHONE, DOCUMENT_ID, CREATED_AT)
VALUES (SEQ_USERS.NEXTVAL, 'Administrador Aeroportuario', 'admin@airport.local', '{noop}Admin12345', 'ADMIN', '+50200000000', 'ADMIN-001', SYSTIMESTAMP);

INSERT INTO AIRPORTS (ID, NAME, CITY, COUNTRY, IATA_CODE) VALUES (SEQ_AIRPORTS.NEXTVAL, 'La Aurora International Airport', 'Guatemala City', 'Guatemala', 'GUA');
INSERT INTO AIRPORTS (ID, NAME, CITY, COUNTRY, IATA_CODE) VALUES (SEQ_AIRPORTS.NEXTVAL, 'El Salvador International Airport', 'San Salvador', 'El Salvador', 'SAL');
INSERT INTO AIRPORTS (ID, NAME, CITY, COUNTRY, IATA_CODE) VALUES (SEQ_AIRPORTS.NEXTVAL, 'Tocumen International Airport', 'Panama City', 'Panama', 'PTY');

INSERT INTO AIRCRAFT (ID, MODEL, CAPACITY, AIRLINE) VALUES (SEQ_AIRCRAFT.NEXTVAL, 'Airbus A320neo', 30, 'Aero Premium');
INSERT INTO AIRCRAFT (ID, MODEL, CAPACITY, AIRLINE) VALUES (SEQ_AIRCRAFT.NEXTVAL, 'Boeing 737 MAX 8', 36, 'Aero Premium');

INSERT INTO FLIGHTS (ID, ORIGIN_ID, DESTINATION_ID, AIRCRAFT_ID, DEPARTURE_TIME, ARRIVAL_TIME, PRICE, AVAILABLE_SEATS, STATUS)
VALUES (SEQ_FLIGHTS.NEXTVAL, 1, 2, 1, SYSTIMESTAMP + INTERVAL '2' DAY, SYSTIMESTAMP + INTERVAL '2' DAY + INTERVAL '1' HOUR, 185.00, 30, 'SCHEDULED');
INSERT INTO FLIGHTS (ID, ORIGIN_ID, DESTINATION_ID, AIRCRAFT_ID, DEPARTURE_TIME, ARRIVAL_TIME, PRICE, AVAILABLE_SEATS, STATUS)
VALUES (SEQ_FLIGHTS.NEXTVAL, 1, 3, 2, SYSTIMESTAMP + INTERVAL '3' DAY, SYSTIMESTAMP + INTERVAL '3' DAY + INTERVAL '2' HOUR, 310.00, 36, 'SCHEDULED');

BEGIN
  FOR f IN (SELECT ID, AVAILABLE_SEATS FROM FLIGHTS) LOOP
    FOR i IN 1..f.AVAILABLE_SEATS LOOP
      INSERT INTO SEATS (ID, FLIGHT_ID, SEAT_NUMBER, RESERVED)
      VALUES (SEQ_SEATS.NEXTVAL, f.ID, CHR(65 + MOD(i - 1, 6)) || TO_CHAR(FLOOR((i - 1) / 6) + 1), 0);
    END LOOP;
  END LOOP;
END;
/
