CREATE OR REPLACE TRIGGER TRG_USERS_CREATED_AT
BEFORE INSERT ON APP_USERS
FOR EACH ROW
BEGIN
  IF :NEW.CREATED_AT IS NULL THEN
    :NEW.CREATED_AT := SYSTIMESTAMP;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_RESERVATIONS_CREATED_AT
BEFORE INSERT ON RESERVATIONS
FOR EACH ROW
BEGIN
  IF :NEW.CREATED_AT IS NULL THEN
    :NEW.CREATED_AT := SYSTIMESTAMP;
  END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENTS_CREATED_AT
BEFORE INSERT ON PAYMENTS
FOR EACH ROW
BEGIN
  IF :NEW.CREATED_AT IS NULL THEN
    :NEW.CREATED_AT := SYSTIMESTAMP;
  END IF;
END;
/
