ALTER TABLE APP_USERS ADD (
  TITLE VARCHAR2(20),
  GENDER VARCHAR2(20),
  BIRTH_DATE VARCHAR2(20),
  NATIONALITY VARCHAR2(80),
  DOCUMENT_TYPE VARCHAR2(40),
  DOCUMENT_EXPIRATION VARCHAR2(20),
  DOCUMENT_COUNTRY VARCHAR2(80),
  FREQUENT_FLYER VARCHAR2(60)
);

ALTER TABLE RESERVATIONS ADD EMAIL_SENT NUMBER(1) DEFAULT 0 NOT NULL CHECK (EMAIL_SENT IN (0,1));
