ALTER SESSION SET CONTAINER=FREEPDB1;

CREATE USER AIRPORT_APP IDENTIFIED BY Airport12345 QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE VIEW, CREATE PROCEDURE TO AIRPORT_APP;
